### ISSUE TITLE
Front-end design

### ISSUE THREAD

**Issue by sedouard** [sedouard/slack-o365-calendar#12]
Currently the login page is ugly, and the login success is lame too.
- Create a page with a nice 'Login with Azure Active Direcotry' button
- After the oauth returns to the '/succeeded' route, make a nice page saying that their o365 busy/free time will be sync'd to slack.

Use either a nice bootstrap library or http://materializecss.com/ which is also really nice to create a pretty page

**Comment by isalento** [comment]
I'll work on this!

**Comment by sedouard** [comment]
via https://github.com/sedouard/slack-o365-calendar/pull/20
